### ISSUE TITLE
Make the project executable whitout IDE

### ISSUE THREAD

**Issue by Matushl** [domhanak/neural-networks#6]
program must compile and execute either on Linux or on Windows _without_ any IDE.
Please add a text file describing what is necessary to compile and execute your code.

**Comment by domhanak** [comment]
Hey, Matus, can you give me list of necessary attributes we want to be able to use in execution?

**Comment by domhanak** [comment]
Project is excutable without IDE.
Uses MAVEN. 
1. Compile and build mvn clean compile -DskipTests
2. Run the application using mvn exec:java
